# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tolmo < Formula
  desc "CLI for the Tolmo platform"
  homepage "https://github.com/tolmohq/tolmo"
  version "0.33.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tolmohq/tolmo/releases/download/v0.33.1/tolmo_0.33.1_darwin_amd64.tar.gz"
      sha256 "f0f6df49df1369ccf13d4d5467317d5f01636641cb2f31b3479f7b09c4cb99a6"

      define_method(:install) do
        bin.install "tolmo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tolmohq/tolmo/releases/download/v0.33.1/tolmo_0.33.1_darwin_arm64.tar.gz"
      sha256 "cd3b594d7c367df1d71ce34e114dac17966bd3cff8003078b2ce803d82e2f716"

      define_method(:install) do
        bin.install "tolmo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tolmohq/tolmo/releases/download/v0.33.1/tolmo_0.33.1_linux_amd64.tar.gz"
      sha256 "3ec3ff61efaaa3890520ace3f74e0ea35cd1a0ac38fdf13414b98a3a337b9d78"
      define_method(:install) do
        bin.install "tolmo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tolmohq/tolmo/releases/download/v0.33.1/tolmo_0.33.1_linux_arm64.tar.gz"
      sha256 "6ebd185cf81df83d2b462fed979e8f22f34ebf391bd52f5474995c2036ebdd36"
      define_method(:install) do
        bin.install "tolmo"
      end
    end
  end

  def caveats
    <<~EOS
      Tolmo does not install agent skills automatically.

      To install or update the embedded Tolmo skill with explicit consent, run:
        tolmo skill install

      Tolmo will install the skill into:
        ~/.claude/skills/tolmo
        ~/.agents/skills/tolmo
    EOS
  end

  test do
    system "#{bin}/tolmo", "--version"
  end
end
