# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TolmoNightly < Formula
  desc "Nightly CLI for the Tolmo platform"
  homepage "https://github.com/tolmohq/tolmo"
  version "0.5.2-nightly.20260523060257.3078832e"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tolmohq/tolmo/releases/download/v0.5.2-nightly.20260523060257.3078832e/tolmo-nightly_0.5.2-nightly.20260523060257.3078832e_darwin_amd64.tar.gz"
      sha256 "083dc942a07c95a2f28150dbe4a4bcf30bf4145f459b3c4db2fa27fbaecab6cc"

      define_method(:install) do
        bin.install "tolmo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tolmohq/tolmo/releases/download/v0.5.2-nightly.20260523060257.3078832e/tolmo-nightly_0.5.2-nightly.20260523060257.3078832e_darwin_arm64.tar.gz"
      sha256 "8e23bd9029129e2a6b094fbb20180ea4dc49a206a221ea121c94200dc7af1d62"

      define_method(:install) do
        bin.install "tolmo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tolmohq/tolmo/releases/download/v0.5.2-nightly.20260523060257.3078832e/tolmo-nightly_0.5.2-nightly.20260523060257.3078832e_linux_amd64.tar.gz"
      sha256 "a613a30581d8ecfb731bf1e4d8322cc5a0da09f2da622d0a6039182720389a32"
      define_method(:install) do
        bin.install "tolmo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tolmohq/tolmo/releases/download/v0.5.2-nightly.20260523060257.3078832e/tolmo-nightly_0.5.2-nightly.20260523060257.3078832e_linux_arm64.tar.gz"
      sha256 "7bff22505d25ba83f870ec457345fe8d7e968767b33a4090eefd85b76525a8cc"
      define_method(:install) do
        bin.install "tolmo"
      end
    end
  end

  def caveats
    <<~EOS
      Tolmo does not install agent skills automatically.

      To install or update the embedded Tolmo skill with explicit consent, run:
        tolmo skill install

      Tolmo will install the skill into:
        ~/.claude/skills/tolmo
        ~/.agents/skills/tolmo
    EOS
  end

  test do
    system "#{bin}/tolmo", "--version"
  end
end
