# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tolmo < Formula
  desc "CLI for the Tolmo platform"
  homepage "https://github.com/tolmohq/tolmo"
  version "0.8.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tolmohq/tolmo/releases/download/v0.8.2/tolmo_0.8.2_darwin_amd64.tar.gz"
      sha256 "d957c53207a121bc7fe4ae668a9f54d55a157cbae32d23292371e8b0448efc85"

      define_method(:install) do
        bin.install "tolmo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tolmohq/tolmo/releases/download/v0.8.2/tolmo_0.8.2_darwin_arm64.tar.gz"
      sha256 "d9bf850a85fde78229f1b27b649486d7f8102963406a88c2eaa00040db983a92"

      define_method(:install) do
        bin.install "tolmo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tolmohq/tolmo/releases/download/v0.8.2/tolmo_0.8.2_linux_amd64.tar.gz"
      sha256 "e0a5925494a786832d46705cb1594189481f15257704f98fad6b59ffa8a20057"
      define_method(:install) do
        bin.install "tolmo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tolmohq/tolmo/releases/download/v0.8.2/tolmo_0.8.2_linux_arm64.tar.gz"
      sha256 "89e07c4a34a3698fbf3795dde9e0532c66d83e9e54bc5838f210994f69d1b852"
      define_method(:install) do
        bin.install "tolmo"
      end
    end
  end

  def caveats
    <<~EOS
      Tolmo does not install agent skills automatically.

      To install or update the embedded Tolmo skill with explicit consent, run:
        tolmo skill install

      Tolmo will install the skill into:
        ~/.claude/skills/tolmo
        ~/.agents/skills/tolmo
    EOS
  end

  test do
    system "#{bin}/tolmo", "--version"
  end
end
