# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TolmoNightly < Formula
  desc "Nightly CLI for the Tolmo platform"
  homepage "https://github.com/tolmohq/tolmo"
  version "0.8.0-nightly.20260531062950.b60479f0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tolmohq/tolmo/releases/download/v0.8.0-nightly.20260531062950.b60479f0/tolmo-nightly_0.8.0-nightly.20260531062950.b60479f0_darwin_amd64.tar.gz"
      sha256 "bd51f3451f363c463dca312f9c6105823fd3fb4103d40ae5dfd59e3f7169cb72"

      define_method(:install) do
        bin.install "tolmo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tolmohq/tolmo/releases/download/v0.8.0-nightly.20260531062950.b60479f0/tolmo-nightly_0.8.0-nightly.20260531062950.b60479f0_darwin_arm64.tar.gz"
      sha256 "abf83679770bc8c9af0ac088135f5727c3ded76195f27fd47c6a4607eff16af4"

      define_method(:install) do
        bin.install "tolmo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tolmohq/tolmo/releases/download/v0.8.0-nightly.20260531062950.b60479f0/tolmo-nightly_0.8.0-nightly.20260531062950.b60479f0_linux_amd64.tar.gz"
      sha256 "0f58af6a89e947cf7dfd46980c6cc734f58956c28fbc0a3f21168e588e129245"
      define_method(:install) do
        bin.install "tolmo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tolmohq/tolmo/releases/download/v0.8.0-nightly.20260531062950.b60479f0/tolmo-nightly_0.8.0-nightly.20260531062950.b60479f0_linux_arm64.tar.gz"
      sha256 "fb471339645b542fdd64011a68ad3ff781b1e9f606b41578ad584395e314d5c4"
      define_method(:install) do
        bin.install "tolmo"
      end
    end
  end

  def caveats
    <<~EOS
      Tolmo does not install agent skills automatically.

      To install or update the embedded Tolmo skill with explicit consent, run:
        tolmo skill install

      Tolmo will install the skill into:
        ~/.claude/skills/tolmo
        ~/.agents/skills/tolmo
    EOS
  end

  test do
    system "#{bin}/tolmo", "--version"
  end
end
