# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TolmoNightly < Formula
  desc "Nightly CLI for the Tolmo platform"
  homepage "https://github.com/tolmohq/tolmo"
  version "0.23.0-nightly.20260714054651.1e5dd074"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tolmohq/tolmo/releases/download/v0.23.0-nightly.20260714054651.1e5dd074/tolmo-nightly_0.23.0-nightly.20260714054651.1e5dd074_darwin_amd64.tar.gz"
      sha256 "21000f9f318d5116030f077f70fc1cfb3e7b8abc6fa075ac932bf087891232ff"

      define_method(:install) do
        bin.install "tolmo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tolmohq/tolmo/releases/download/v0.23.0-nightly.20260714054651.1e5dd074/tolmo-nightly_0.23.0-nightly.20260714054651.1e5dd074_darwin_arm64.tar.gz"
      sha256 "67ed1ce6c64d90293ee3f1d2f97cd6ec391bc7efd839cfaadb4cd42706a72710"

      define_method(:install) do
        bin.install "tolmo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tolmohq/tolmo/releases/download/v0.23.0-nightly.20260714054651.1e5dd074/tolmo-nightly_0.23.0-nightly.20260714054651.1e5dd074_linux_amd64.tar.gz"
      sha256 "8636663e499ac765dc02e36c81aff876e92a5a061bd864d26247f5d4b870c3b4"
      define_method(:install) do
        bin.install "tolmo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tolmohq/tolmo/releases/download/v0.23.0-nightly.20260714054651.1e5dd074/tolmo-nightly_0.23.0-nightly.20260714054651.1e5dd074_linux_arm64.tar.gz"
      sha256 "bd29690912b9b26b4823f3853c4925be8c2e6abd20c94d537b647d46c164c645"
      define_method(:install) do
        bin.install "tolmo"
      end
    end
  end

  def caveats
    <<~EOS
      Tolmo does not install agent skills automatically.

      To install or update the embedded Tolmo skill with explicit consent, run:
        tolmo skill install

      Tolmo will install the skill into:
        ~/.claude/skills/tolmo
        ~/.agents/skills/tolmo
    EOS
  end

  test do
    system "#{bin}/tolmo", "--version"
  end
end
