# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tolmo < Formula
  desc "CLI for the Tolmo platform"
  homepage "https://github.com/tolmohq/tolmo"
  version "0.33.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tolmohq/tolmo/releases/download/v0.33.0/tolmo_0.33.0_darwin_amd64.tar.gz"
      sha256 "ac909286a51a3c72f6780081c997e380077c0693441dc415ae314c2303508cc4"

      define_method(:install) do
        bin.install "tolmo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tolmohq/tolmo/releases/download/v0.33.0/tolmo_0.33.0_darwin_arm64.tar.gz"
      sha256 "305c8cb683534f1ff22e63afb96f5c95ae0470e39fe371eeb1913f6f12f8d3df"

      define_method(:install) do
        bin.install "tolmo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tolmohq/tolmo/releases/download/v0.33.0/tolmo_0.33.0_linux_amd64.tar.gz"
      sha256 "426151339717deb16e8e024fe546bd3b023555060b57f25e1563dbe5c98b85a0"
      define_method(:install) do
        bin.install "tolmo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tolmohq/tolmo/releases/download/v0.33.0/tolmo_0.33.0_linux_arm64.tar.gz"
      sha256 "a72e6cae7e0f0306554bda1ebbd11e037a6619f49749b5ba17a5ae3a9eb494eb"
      define_method(:install) do
        bin.install "tolmo"
      end
    end
  end

  def caveats
    <<~EOS
      Tolmo does not install agent skills automatically.

      To install or update the embedded Tolmo skill with explicit consent, run:
        tolmo skill install

      Tolmo will install the skill into:
        ~/.claude/skills/tolmo
        ~/.agents/skills/tolmo
    EOS
  end

  test do
    system "#{bin}/tolmo", "--version"
  end
end
