# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tolmo@nightly < Formula
  desc "Nightly CLI for the Tolmo platform"
  homepage "https://github.com/tolmohq/tolmo"
  version "0.3.0-nightly.20260410054300.28b23ca0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tolmohq/tolmo/releases/download/v0.3.0-nightly.20260410054300.28b23ca0/tolmo-nightly_0.3.0-nightly.20260410054300.28b23ca0_darwin_amd64.tar.gz"
      sha256 "4b08b34fc3b4e5bb5570e15b15438e93084f21e58bfa7ecf3b54f6e11a3251bb"

      define_method(:install) do
        bin.install "tolmo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tolmohq/tolmo/releases/download/v0.3.0-nightly.20260410054300.28b23ca0/tolmo-nightly_0.3.0-nightly.20260410054300.28b23ca0_darwin_arm64.tar.gz"
      sha256 "12150f62bc0633b41e265515b4cb515ca51f2486a41c23dbae17426cbc9c69ce"

      define_method(:install) do
        bin.install "tolmo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tolmohq/tolmo/releases/download/v0.3.0-nightly.20260410054300.28b23ca0/tolmo-nightly_0.3.0-nightly.20260410054300.28b23ca0_linux_amd64.tar.gz"
      sha256 "3001c1c89af1bd47a123dc7505bf7f0a091320848a8d5cb67863831bc309586d"
      define_method(:install) do
        bin.install "tolmo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tolmohq/tolmo/releases/download/v0.3.0-nightly.20260410054300.28b23ca0/tolmo-nightly_0.3.0-nightly.20260410054300.28b23ca0_linux_arm64.tar.gz"
      sha256 "9dac3e3b5c285bef957921e80ca0dc03cf09188a251281017413fb1b1394ea3a"
      define_method(:install) do
        bin.install "tolmo"
      end
    end
  end

  test do
    system "#{bin}/tolmo", "--version"
  end
end
